
var codeSnippets = {

	"JS-innerHTML" : {

		"html" : [
			"<div id=\"segment\" onclick=\"callMe()\">",
			"	Hello" ,
			"</div>"
		],

		"css" : [
			"#segment{",
			"	background-color:green;" ,
			"	padding:25px;" ,
			"	width:100px;" ,
			"	height:100px;" ,
			"	font-weight:bold;" ,
			"}"
		],

		"js" : [
			"function callMe(){" ,
			"	document.getElementById(\"segment\").innerHTML = \"Hello world\";" ,
			"}"
		]

	},
	"JS-HTMLStyles" : {

		"html" : [
			"<div id=\"segment\" onclick=\"callMe()\">",
			"	Hello" ,
			"</div>"
		],

		"css" : [
			"#segment{",
			"	background-color:green;" ,
			"	padding:25px;" ,
			"	width:100px;" ,
			"	height:100px;" ,
			"	font-weight:bold;" ,
			"}"
		],

		"js" : [
			"function callMe(){" ,
			"	document.getElementById(\"segment\").style.background=\"gold\";" ,
			"}"
		]

	},
	"JS-DocumentWrite" : {

		"html" : [
			"<div id=\"segment\" onclick=\"callMe()\">",
			"	Hello" ,
			"</div>"
		],

		"css" : [
			"#segment{",
			"	background-color:green;" ,
			"	padding:25px;" ,
			"	width:100px;" ,
			"	height:100px;" ,
			"	font-weight:bold;" ,
			"}"
		],

		"js" : [
			"function callMe(){",
			"	document.write(\"I am fine. How are you?\");",
			"}"
		]

	},
	"JS-alert" : {

		"html" : [
			"<div id=\"segment\" onclick=\"callMe()\">",
			"	Hello" ,
			"</div>"
		],

		"css" : [
			"#segment{",
			"	background-color:green;" ,
			"	padding:25px;" ,
			"	width:100px;" ,
			"	height:100px;" ,
			"	font-weight:bold;" ,
			"}"
		],

		"js" : [
			"function callMe(){",
			"	alert(\"Howdy\");",
			"}"
		]

	},
	"JS-console.log" : {

		"html" : [
			"<div id=\"segment\" onclick=\"callMe()\">",
			"	Hello" ,
			"</div>"
		],

		"css" : [
			"#segment{",
			"	background-color:green;" ,
			"	padding:25px;" ,
			"	width:100px;" ,
			"	height:100px;" ,
			"	font-weight:bold;" ,
			"}"
		],

		"js" : [
			"function callMe(){",
			"	//Using parent.console, because the code is going to run from an iframe",
			"	parent.console.log(\"Howdy\");",
			"}"
		]

	},
	"JS-events" : {

		"html" : [
			"<table>",
			"	<tr>",
			"		<td>",
			"			<img src=\"images/download.png\" onload=\"loadImage()\" width=\"150\" height=\"132\"></img>",
			"		</td>",
			"		<td>",
			"			<div id=\"onloadId\"></div>",
			"		</td>",
			"	</tr>",
			"	<tr>",
			"		<td>",
			"			<div class=\"segment\" onclick=\"callMe('click!!','clickDisp')\">",
			"				click",
			"			</div>",
			"		</td>",
			"		<td>",
			"			<span id=\"clickDisp\"></span>",
			"		</td>",
			"	</tr>",
			"	<tr>",
			"		<td>",
			"			<div class=\"segment\" onmouseover=\"callMe('mouse over!!','moverDisp')\">",
			"				mouse over ",
			"			</div>",
			"		</td>",
			"		<td>",
			"			<span id=\"moverDisp\"></span>",
			"		</td>",
			"	</tr>",
			"	<tr>",
			"		<td>",
			"			<div class=\"segment\" onmouseout=\"callMe('mouse out!!','moutDisp')\">",
			"				mouse out",
			"			</div>",
			"		</td>",
			"		<td>",
			"			<span id=\"moutDisp\"></span>",
			"		<td/>",
			"	</tr>",
			"	<tr>",
			"		<td>",
			"			<input onkeydown=\"callMe('keydown!!','keydownDisp')\" type=\"text\"</input>",
			"		</td>",
			"		<td>",
			"			<span id=\"keydownDisp\"></span>",
			"		</td>",
			"	</tr>",
			"<!-- Once the value is changed , click outside -->",
			"	<tr>",
			"		<td>",
			"			<input onchange=\"callMe('change!!','onChangeDisp')\" type=\"text\">",
			"</input>",
			"		</td>",
			"		<td>",
			"			<span id=\"onChangeDisp\"></span>",
			"		</td>",
			"	</tr>",
			"</table>"
		],

		"css" : [
			".segment{",
			"	background-color:green;" ,
			"	padding:25px;" ,
			"	width:150px;" ,
			"	height:30px;" ,
			"	font-weight:bold;" ,
			"	margin:10px;" ,
			"}",
			"",
			"td{",
			"	padding:3px;",
			"}"
		],

		"js" : [
			"function loadImage(){",
			"	document.getElementById(\"onloadId\").innerHTML = \"onload done\";",
			"}",
			"function callMe(str,id){",
			"	document.getElementById(id).innerHTML = str;",
			"}"
		]

	},
	"JS-strings" : {

		"html" : [
			"<div id=\"segment\" onclick=\"callMe()\">",
			"	This is a sample text. Click on this text to see some string functions in action.",
			"</div>",
			"",
			"<table>",
			"	<tr>",
			"		<td>total Length</td>",
			"	<td id=\"totalLength\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>first occurence of 'text'</td>",
			"		<td id=\"firstIndex\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>last occurence of 'text'</td>",
			"		<td id=\"lastIndex\"> </td>",
			"	</tr>",
			"<!-- search can take regular expressions, but indexOf cannot -->",
			"	<tr>",
			"		<td>'actions' is present at</td>",
			"		<td id=\"actions\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>'action' is present at</td>",
			"		<td id=\"action\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>text after using substring from 25  to 30</td>",
			"		<td id=\"subString\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>text after using substr from 25 to length 5</td>",
			"		<td id=\"subStr\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>text after slicing from 25 till the end</td>",
			"		<td id=\"slice\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>character at position 22</td>",
			"		<td id=\"charAt\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>after replacing first occurrence of 'text' with 'string'</td>",
			"		<td id=\"replace\"></td>",
			"	</tr>",
			"	<tr>",
			"		<td>all to upper case</td>",
			"		<td id=\"upper\"></td>",
			"	</tr>",
			"	<tr>",
			"		<td>all to lower case</td>",
			"		<td id=\"lower\"></td>",
			"	</tr>",
			"	<tr>",
			"	<td>concat two strings (Hello + world)</td>",
			"	<td id=\"concat\"></td>",
			"	</tr>",
			"</table>"
		],

		"css" : [
			"#segment{",
			"	margin:25px;",
			"	font-weight:bold;",
			"	cursor:pointer;",
			"	background-color:grey;",
			"}",
			"",
			"td{",
			"	border:1px solid black;",
			"}",
			"",
			"body{",
			"	padding:5px;",
			"}"
		],

		"js" : [
			"function callMe(){",
			"	var orgText = document.getElementById(\"segment\").innerHTML;",
			"	document.getElementById(\"totalLength\").innerHTML = orgText.length;",
			"	document.getElementById(\"firstIndex\").innerHTML = orgText.indexOf(\"text\");",
			"	document.getElementById(\"lastIndex\").innerHTML = orgText.lastIndexOf(\"text\");",
			"	document.getElementById(\"actions\").innerHTML = orgText.search(\"actions\");",
			"	document.getElementById(\"action\").innerHTML = orgText.search(\"action\");",
			"	document.getElementById(\"subString\").innerHTML = orgText.substring(25,30);",
			"	document.getElementById(\"subStr\").innerHTML = orgText.substr(25,5);",
			"	document.getElementById(\"slice\").innerHTML = orgText.slice(25);",
			"	document.getElementById(\"charAt\").innerHTML = orgText.charAt(22);",
			"	document.getElementById(\"replace\").innerHTML = orgText.replace('text','string');",
			"	document.getElementById(\"upper\").innerHTML = orgText.toUpperCase();",
			"	document.getElementById(\"lower\").innerHTML = orgText.toLowerCase();",
			"	document.getElementById(\"concat\").innerHTML = 'Hello'.concat('world');",
			"}"
		]

	},
	"JS-===" : {

		"html" : [
			"<div>",
			"	var x = 10;",
			"	<br/><br/>",
			"	var y = new Number(10);",
			"	<br/><br/>",
			"	<button onclick=\"callMe()\">Are we both the same? </button>",
			"	<br/>",
			"	<br/>",
			"	Compared based on value:",
			"	<span id=\"value\"></span>",
			"	<br/>",
			"	Compared based on type and value:",
			"	<span id=\"typeandvalue\"></span>",
			"</div>"
		],

		"css" : [
		],

		"js" : [
			"function callMe(){",
			"	var x = 10;",
			"	var y = new Number(10);",
			"	document.getElementById(\"value\").innerHTML = (x==y);",
			"	document.getElementById(\"typeandvalue\").innerHTML = (x===y);",
			"}"
		]

	},
	"JS-NaN" : {

		"html" : [
			"<p>Please enter a number</p>",
			"<input id=\"numb\" type=\"text\">",
			"<button type=\"button\" onclick=\"callMe()\">Validate</button>",
			"<p id=\"result\"></p>"
		],

		"css" : [
		],

		"js" : [
			"function callMe() {",
			"   var x, text;",
			"    x = document.getElementById(\"numb\").value;",
			"   if (isNaN(x)) {",
			"        text = \"Enter only a number\";",
			"    } else {",
			"        text = \"Input OK\";",
			"    }",
			"    document.getElementById(\"result\").innerHTML = text;",
			"}"
		]

	},
	"JS-Numbers" : {

		"html" : [
			"<button onclick=\"callMe()\">Process</button>",
			"<br/>",
			"<br/>",
			"<table>",
			"	<tr>",
			"		<td>convert 100 + 23 to string</td>",
			"		<td id=\"toString\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>round off 100.54 to 0 decimals</td>",
			"		<td id=\"0demical\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>round off 100.56 to 1 decimal</td>",
			"		<td id=\"1demical\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>set precision / length of 100 to 6</td>",
			"		<td id=\"length\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>convert true to Number</td>",
			"		<td id=\"true\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>convert string 100 1 to Number</td>",
			"		<td id=\"string\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>convert string 1001 to Number</td>",
			"		<td id=\"properStr\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>parse \"100 years\"</td>",
			"		<td id=\"parse\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>parse \"years 100\"</td>",
			"		<td id=\"parseIncorrect\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>parse \"100.452\"</td>",
			"		<td id=\"parseFloatVal\"></td>",
			"	</tr>",
			"	<tr>",
			"		<td>parse float \"100.452\"</td>",
			"		<td id=\"parseFloat\"></td>",
			"	</tr>",
			"</table>"
		],

		"css" : [
			"td{",
			"	border:1px solid black;",
			"}",
			"",
			"body{",
			"	padding:5px;",
			"}"
		],

		"js" : [
			"function callMe(){",
			"	document.getElementById(\"toString\").innerHTML = (100 + 23).toString();",
			"	document.getElementById(\"0demical\").innerHTML = (100.54).toFixed(0);",
			"	document.getElementById(\"1demical\").innerHTML = (100.56).toFixed(1);",
			"	document.getElementById(\"length\").innerHTML = (100).toPrecision(6);",
			"	document.getElementById(\"true\").innerHTML = Number(true);",
			"	document.getElementById(\"string\").innerHTML = Number(\"100 1\");",
			"	document.getElementById(\"properStr\").innerHTML =  Number(\"1001\");",
			"	document.getElementById(\"parse\").innerHTML = parseInt(\"100 years\");",
			"	document.getElementById(\"parseIncorrect\").innerHTML = parseInt(\"years 100\");",
			"	document.getElementById(\"parseFloatVal\").innerHTML = parseInt(\"100.452\");",
			"	document.getElementById(\"parseFloat\").innerHTML = parseFloat(\"100.452\");",
			"}"
		]

	},
	"JS-tryCatch" : {

		"html" : [
			"<div id=\"segment\" onclick=\"callMe()\">",
			"</div>",
			"<div id=\"message\">",
			"</div>",
			"<div id=\"finallymessage\">",
			"</div>"
		],

		"css" : [
			"#segment{",
			"	background-color:green;",
			"	padding:25px;",
			"	width:80px;",
			"	height:30px;",
			"	font-weight:bold;",
			"	margin:10px;",
			"}"
		],

		"js" : [
			"function callMe(str,id){",
			"	try{",
			"		document.getElementById(\"segments\").innerHTML = \"Hello\";",
			"	}catch(e){",
			"		document.getElementById(\"message\").innerHTML = \"Error\";",
			"	}finally{",
			"		document.getElementById(\"finallymessage\").innerHTML = \"Finally called\";",
			"	}",
			"}"
		]

	},
	"JS-array" : {

		"html" : [
			"<div class=\"segment inline\" onclick=\"split()\">",
			"	Split and change a,n,b to a|n|b",
			"</div>",
			"",
			"<div class=\"inline\" id=\"split\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"length()\">",
			"	Length of [1,4,5,6]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"length\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"index()\">",
			"	Element at index 2 of array [1,4,5,6]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"index\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"sort()\">",
			"	Sort ['a','n','b']",
			"</div>",
			"",
			"<div class=\"inline\" id=\"sort\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"reverseTest()\">",
			"	Reverse ['a','n','b']",
			"</div>",
			"",
			"<div class=\"inline\" id=\"reverseTest\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"sortNumInc()\">",
			"	Sort [1,43,5,8,7]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"sortNumInc\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"sortNumProper()\">",
			"	Sort [1,43,2,3]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"sortNumProper\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"toStringTest()\">",
			"	 [1,43,2,3] to string",
			"</div>",
			"",
			"<div class=\"inline\" id=\"toString\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"valueOfTest()\">",
			"	 value of [1,43,2,3]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"valueOf\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"afterPush()\">",
			"	 after pushing 7 in [1,43,2,3]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"afterPush\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"afterPop()\">",
			"	 after popping array [1,43,2,3]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"afterPop\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"shiftTest()\">",
			"	 shift array [1,43,2,3]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"shiftTest\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"unshiftTest()\">",
			"	un shift  5 to array [1,43,2,3]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"unshiftTest\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"deleteTest()\">",
			"	delete index 2 in array [1,43,2,3]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"deleteTest\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"spliceTest()\">",
			"	Splice in 5 at index 2 in [1,43,2,3]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"spliceTest\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"spliceOutTest()\">",
			"	Splice out elem at index 2 in [1,43,2,3]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"spliceOutTest\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"concatTest()\">",
			"	Concat arrays [1,43,2,3] and [21,243,22,23]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"concatTest\"></div>",
			"",
			"<br/>",
			"",
			"<div class=\"segment inline\" onclick=\"sliceTest()\">",
			"	Slice 43 and 2 into another array from [1,43,2,3]",
			"</div>",
			"",
			"<div class=\"inline\" id=\"sliceTest\"></div>",
			"",
			"<br/>"
		],

		"css" : [
			".segment{",
			"	background-color:powderBlue;",
			"	width:250px;",
			"	font-weight:bold;",
			"	margin:5px;",
			"	padding:2px;",
			"	cursor:pointer;",
			"}",
			"",
			".inline{",
			"	display:inline-block;",
			"}"
		],

		"js" : [
			"function split(){",
			"	var arr = \"a,n,b\";",
			"	arr =  arr.split(\",\");",
			"	document.getElementById(\"split\").innerHTML = arr.join(\"|\");",
			"}",
			"",
			"function length(){",
			"	var arr =  [1,4,5,6];",
			"	document.getElementById(\"length\").innerHTML = arr.length;",
			"}",
			"",
			"function index(){",
			"	var arr =  [1,4,5,6];",
			"	document.getElementById(\"index\").innerHTML = arr[2];",
			"}",
			"",
			"function sort(){",
			"	var arr =  ['a','n','b'];",
			"	document.getElementById(\"sort\").innerHTML = arr.sort();",
			"}",
			"",
			"function reverseTest(){",
			"	var arr =  ['a','n','b'];",
			"	document.getElementById(\"reverseTest\").innerHTML = arr.reverse();",
			"}",
			"",
			"",
			"function sortNumInc(){",
			"	var arr = [1,43,5,8,7];",
			"	document.getElementById(\"sortNumInc\").innerHTML = arr.sort();",
			"}",
			"",
			"function sortNumProper(){",
			"	var arr =  [1,43,2,3];",
			"	document.getElementById(\"sortNumProper\").innerHTML = arr.sort(function(a,b){return a-b});",
			"}",
			"",
			"function toStringTest(){",
			"	var arr = [1,43,2,3];",
			"	document.getElementById(\"toString\").innerHTML = arr.toString();",
			"}",
			"",
			"function valueOfTest(){",
			"	var arr = [1,43,2,3];",
			"	document.getElementById(\"valueOf\").innerHTML = arr.valueOf();",
			"}",
			"",
			"function afterPush(){",
			"	var arr = [1,43,2,3];",
			"	arr.push(7);",
			"	document.getElementById(\"afterPush\").innerHTML = arr.valueOf();",
			"}",
			"",
			"function afterPop(){",
			"	var arr = [1,43,2,3];",
			"	var x = arr.pop();",
			"	document.getElementById(\"afterPop\").innerHTML = arr.valueOf() + \"  and the popped element is \" + x;",
			"}",
			"",
			"function shiftTest(){",
			"	var arr = [1,43,2,3];",
			"	var x = arr.shift();",
			"	document.getElementById(\"shiftTest\").innerHTML = arr.valueOf() + \"  and the shifted element is \" + x;",
			"}",
			"",
			"function unshiftTest(){",
			"	var arr = [1,43,2,3];",
			"	var x = arr.unshift(5);",
			"	document.getElementById(\"unshiftTest\").innerHTML = arr.valueOf();",
			"}",
			"",
			"function deleteTest(){",
			"	var arr = [1,43,2,3];",
			"	delete arr [2];",
			"	document.getElementById(\"deleteTest\").innerHTML = arr.valueOf();",
			"}",
			"",
			"function spliceTest(){",
			"	var arr = [1,43,2,3];",
			"	arr.splice(2,0,5); \/\/first param - index, second param - no of elems to remove",
			"	document.getElementById(\"spliceTest\").innerHTML = arr.valueOf();",
			"}",
			"",
			"function spliceOutTest(){",
			"	var arr = [1,43,2,3];",
			"	arr.splice(2,1); ",
			"	document.getElementById(\"spliceOutTest\").innerHTML = arr.valueOf();",
			"}",
			"",
			"function concatTest(){",
			"	var arr = [1,43,2,3];",
			"	var arr2 =  [21,243,22,23];",
			"	var arr3 = arr.concat(arr2);",
			"	document.getElementById(\"concatTest\").innerHTML = arr3.valueOf();",
			"}",
			"",
			"function sliceTest(){",
			"	var arr = [1,43,2,3];",
			"	var arr2 = arr.slice(1,3);\/\/ second argument is ending index, it does not include it",
			"	document.getElementById(\"sliceTest\").innerHTML = arr2.valueOf() + \" and the original array is \" + arr.valueOf();",
			"}"
		]

	},
	"JS-Math" : {

		"html" : [
			
				"<div class=\"segment inline\" onclick=\"random()\">",
				"	Get me a random number",
				"</div>",
				"",
				"<div class=\"inline\" id=\"random\">",
				"</div>",
				"",
				"<br/>",
				"",
				"<div class=\"segment inline\" onclick=\"min()\" >",
				"	Get the minimum of (10, 54, 9, 100)",
				"</div>",
				"",
				"<div class=\"inline\" id=\"min\">",
				"</div>",
				"",
				"<br/>",
				"",
				"<div class=\"segment inline\" onclick=\"max()\">",
				"	Get the maximum of (10, 54, 9, 100)",
				"</div>",
				"",
				"<div class=\"inline\" id=\"max\">",
				"</div>",
				"",
				"<br/>",
				"",
				"<div class=\"segment inline\" onclick=\"round()\">",
				"	Round off 4.7 and 2.1 to nearest integer",
				"</div>",
				"",
				"<div class=\"inline\" id=\"round\">",
				"</div>",
				"",
				"<br/>",
				"",
				"<div class=\"segment inline\" onclick=\"ceil()\">",
				"	Round off 4.7 and 2.1 up to the nearest integer",
				"</div>",
				"",
				"<div class=\"inline\" id=\"ceil\">",
				"</div>",
				"",
				"<br/>",
				"",
				"",
				"<div class=\"segment inline\" onclick=\"floor()\">",
				"	Round off 4.7 and 2.1 down to the nearest integer",
				"</div>",
				"",
				"<div class=\"inline\" id=\"floor\">",
				"</div>",
				"",
				"<br/>"
		],

		"css" : [
				".segment{",
				"	background-color:powderBlue;",
				"	width:250px;",
				"	font-weight:bold;",
				"	margin:10px;",
				"	padding:2px;",
				"	cursor:pointer;",
				"}",
				"",
				".inline{",
				"	display:inline-block;",
				"}"
		],

		"js" : [
			"function random(){",
			"	document.getElementById(\"random\").innerHTML = Math.random();",
			"}",
			"",
			"function min(){",
			"	document.getElementById(\"min\").innerHTML = Math.min(10, 54, 9, 100);",
			"}",
			"",
			"function max(){",
			"	document.getElementById(\"max\").innerHTML = Math.max(10, 54, 9, 100);",
			"}",
			"",
			"function round(){",
			"	document.getElementById(\"round\").innerHTML = Math.round(4.7) + \" and \" + Math.round(2.1);",
			"}",
			"",
			"function ceil(){",
			"	document.getElementById(\"ceil\").innerHTML = Math.ceil(4.7) + \" and \" + Math.ceil(2.1);",
			"}",
			"",
			"function floor(){",
			"	document.getElementById(\"floor\").innerHTML = Math.floor(4.7) + \" and \" + Math.floor(2.1);",
			"}"

		]

	},
	"JS-Date" : {

		"html" : [
			"<br/>",
			"<strong>This is the current date : </strong>",
			"<span id=\"demo\" class=\"segment inline\"></span>",
			"<br/><br/>",
			"The year is <span id=\"year\"></span>",
			"<br/>",
			"The date is <span id=\"date\"></span>",
			"<br/>",
			"The hours is <span id=\"hours\"></span>",
			"<br/>",
			"The milli seconds is <span id=\"ms\"></span>",
			"<br/>",
			"The minutes is <span id=\"mins\"></span>",
			"<br/>",
			"The month is <span id=\"months\"></span>",
			"<br/>",
			"The seconds is <span id=\"secs\"></span>",
			"<br/>",
			"The time is <span id=\"time\"></span>",
			"<br/>",
			"Parse the date to ms <span id=\"parse\"></span>",
			"<br/>",
			"Is Jan 1, 2001 greater than Jan 4, 2001 ",
			"<span id=\"dateChk\"></span>",
			"<br/>",
			"Is Jan 1, 2001 lesser than Jan 4, 2001 ",
			"<span id=\"dateChk1\"></span>",
			"<br/>"
		],

		"css" : [
		],

		"js" : [
			"var d = new Date();",
			"",
			"document.getElementById(\"demo\").innerHTML = Date(d);",
			"document.getElementById(\"year\").innerHTML = d.getFullYear();",
			"document.getElementById(\"date\").innerHTML = d.getDate();",
			"document.getElementById(\"hours\").innerHTML = d.getHours();",
			"document.getElementById(\"ms\").innerHTML = d.getMilliseconds();	",
			"document.getElementById(\"mins\").innerHTML = d.getMinutes();	",
			"document.getElementById(\"months\").innerHTML = d.getMonth();	;",
			"document.getElementById(\"secs\").innerHTML = d.getSeconds();	",
			"document.getElementById(\"time\").innerHTML = d.getTime();",
			"document.getElementById(\"parse\").innerHTML = Date.parse(d);",
			"",
			"var d1 = new Date();",
			"var d2 = new Date();",
			"",
			"d1.setFullYear(2001);",
			"d1.setDate(1);",
			"d1.setMonth(1);",
			"",
			"d2.setFullYear(2001);",
			"d2.setDate(4);",
			"d2.setMonth(1);",
			"",
			"document.getElementById(\"dateChk\").innerHTML = d1 > d2;",
			"document.getElementById(\"dateChk1\").innerHTML = d1 < d2;"
		]

	},
	"JS-typeOf" : {

		"html" : [
			"<button onclick=\"callMe()\">Process</button>",
			"<br/>",
			"<br/>",
			"<table>",
			"	<tr>",
			"		<td>\"Hello\" - This is</td>",
			"		<td id=\"string\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>3.14 - This is</td>",
			"		<td id=\"number\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>NaN - This is</td>",
			"		<td id=\"nan\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>false - This is</td>",
			"		<td id=\"bool\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>[1,2,3,4] - This is</td>",
			"		<td id=\"array\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>{name:'John', age:34} - This is </td>",
			"		<td id=\"obj\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>function () {} - This is</td>",
			"		<td id=\"func\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>undefined - This is</td>",
			"		<td id=\"undefined\"> </td>",
			"	</tr>",
			"	<tr>",
			"		<td>null - This is</td>",
			"		<td id=\"null\"> </td>",
			"	</tr>",
			"</table>"
		],

		"css" : [
			"td{",
			"	border:1px solid black;",
			"	padding:5px;",
			"}",
			"",
			"body{",
			"	padding:5px;",
			"}"
		],

		"js" : [
			"function callMe(){",
			"	document.getElementById(\"string\").innerHTML = typeof \"hello\";",
			"	document.getElementById(\"number\").innerHTML = typeof 3.14;",
			"	document.getElementById(\"nan\").innerHTML = typeof NaN;",
			"	document.getElementById(\"bool\").innerHTML = typeof false;",
			"	document.getElementById(\"array\").innerHTML = typeof  [1,2,3,4];",
			"	document.getElementById(\"obj\").innerHTML = typeof {name:'John', age:34};",
			"	document.getElementById(\"func\").innerHTML = typeof function () {} ;",
			"	document.getElementById(\"undefined\").innerHTML = typeof undefined;",
			"	document.getElementById(\"null\").innerHTML = typeof null;",
			"}"
		]

	},
	"JS-this" : {

		"html" : [
			"<button id=\"divId\" onclick=\"callMe()\">Click Me</button>",
			"",
			"<div id=\"message1\"></div>",
			"",
			"<div id=\"message2\"></div>"
		],

		"css" : [
			"body{",
			"	padding:10px;",
			"}"
		],

		"js" : [
			"function callMe(){",
			"	document.getElementById(\"message1\").innerHTML = \"'this' from the button click \" + this;",
			"	var obj1 = {",
			"		var1 : \"hello\",",
			"		var2 : true,",
			"		fns : function(){",
			"			document.getElementById(\"message2\").innerHTML = \"'this' object variable \" + this.var1;",
			"		}",
			"	};",
			"	obj1.fns();",
			"}"
		]

	},
	"JS-mutable" : {

		"html" : [
			"<button id=\"divId\" onclick=\"callMe()\">Click Me</button>",
			"<br/><br/>",
			"<div>Before changing the value of one object</div>",
			"",
			"<div id=\"message1\"></div>",
			"",
			"<div id=\"message2\"></div>",
			"<br/><br/>",
			"<div>After changing the value of one object</div>",
			"",
			"<div id=\"message3\"></div>",
			"",
			"<div id=\"message4\"></div>"
		],

		"css" : [
			"body{",
			"	padding:10px;",
			"}"
		],

		"js" : [
			"function callMe(){",
			"",
			"	var x = { var1 : 10};",
			"	var y = x;	",
			"",
			"	document.getElementById(\"message1\").innerHTML = \" x is : \" + x.var1;",
			"	document.getElementById(\"message2\").innerHTML = \" y is : \" + y.var1;",
			"",
			"	y.var1 = 11;",
			"",
			"	document.getElementById(\"message3\").innerHTML = \" x is : \" + x.var1;",
			"	document.getElementById(\"message4\").innerHTML = \" y is : \" + y.var1;",
			"}"
		]

	},
	"JS-prototype" : {

		"html" : [
			"<button id=\"divId\" onclick=\"callMe()\">Create Objects</button>",
			"<br/><br/>",
			"<div>Created Objects</div>",
			"",
			"<div id=\"message1\"></div>",
			"",
			"<div id=\"message2\"></div>",
			"<br/><br/>"
		],

		"css" : [
			"body{",
			"	padding:10px;",
			"}"
		],

		"js" : [
			"function callMe(){",
			"",
			"	function objPrototype(first, last, age, eyecolor) {",
			"   		this.firstName = first;",
			"  		this.lastName = last;",
			"    		this.age = age;",
			"    		this.eyeColor = eyecolor;",
			"		this.getFullName = function() {return this.firstName + \" \" + this.lastName;};",
			"	}",
			"",
			"	var me = new objPrototype(\"jane\",\"smith\",25,\"black\");",
			"	var you = new objPrototype(\"john\",\"smith\",22,\"blue\");",
			"",
			"	document.getElementById(\"message1\").innerHTML = \" object 1 is : \" + me.getFullName();",
			"	document.getElementById(\"message2\").innerHTML = \" object 2 is : \" + you.getFullName();",
			"",
			"}"
		]

	},
	"JS-bubblingAndCapturing" : {

		"html" : [
			"<strong>Bubbling</strong>",
			"<div onclick=\"layer1Click()\" class=\"segment\" >",
			"	Layer 1",
			"	<div onclick=\"layer2Click()\" class=\"segment\">",
			"		Layer 2",
			"		<div class=\"segment\" id=\"layer3source\">",
			"			Layer 3 - Click on me",
			"		</div>",
			"	</div>",
			"</div>",
			"",
			"<div id=\"message1\"></div>",
			"",
			"<br/><br/>",
			"<strong>Capturing</strong>",
			"<div class=\"segment\" onclick=\"layerTest1Click()\" >",
			"	Layer 1",
			"	<div onclick=\"layerTest2Click()\" class=\"segment\">",
			"		Layer 2",
			"		<div class=\"segment\" id=\"layer3-1source\">",
			"			Layer 3  - Click on me",
			"		</div>",
			"	</div>",
			"</div>",
			"",
			"<div id=\"message2\"></div>"
		],

		"css" : [
			".segment{",
			"	border:1px solid black;",
			"	padding:5px;",
			"	margin:5px;",
			"	cursor:pointer;",
			"}"
		],

		"js" : [
			"document.getElementById(\"layer3source\").addEventListener('click', function(){document.getElementById(\"message1\").innerHTML+= \" Layer 3 called\";}, false);",
			"",
			"",
			"function layer2Click(){",
			"	document.getElementById(\"message1\").innerHTML += \" Layer 2 called\";",
			"}",
			"",
			"function layer1Click(){",
			"	document.getElementById(\"message1\").innerHTML += \" Layer 1 called\";",
			"}",
			"",
			"document.getElementById(\"layer3-1source\").addEventListener('click', function(){document.getElementById(\"message2\").innerHTML += \" Layer 1 called\";}, true);",
			"",
			"",
			"function layerTest2Click(){",
			"	document.getElementById(\"message2\").innerHTML += \" Layer 2 called\";",
			"}",
			"",
			"function layerTest1Click(){",
			"	document.getElementById(\"message2\").innerHTML += \" Layer 3 called\";",
			"}"
		]

	},
	"JS-domSelection" : {

		"html" : [
			"<br/>",
			"<button onclick=\"callMe()\">Process</button>",
			"",
			"<div class=\"segment\"> Segment 1</div>",
			"",
			"<p class=\"segment\"> Segment 2</p>",
			"",
			"<div class=\"segment1\" id=\"seg3\"> Segment 3</div>",
			"",
			"<img id=\"imgId\" src=\"images/download.png\" width=\"150\" height=\"132\"></img>",
			"",
			"<div id=\"divId\"></div>"
		],

		"css" : [
			".segment{",
			"	background-color:green;",
			"	padding:5px;",
			"	width:250px;",
			"	height:75px;",
			"	font-weight:bold;",
			"	margin:10px;",
			"}",
			"",
			".segment1{",
			"	background-color:gold;",
			"	padding:5px;",
			"	width:250px;",
			"	height:75px;",
			"	font-weight:bold;",
			"	margin:10px;",
			"}",
			"",
			"",
			"img{",
			"	padding-left:10px;",
			"}",
			"",
			"button{",
			"	margin-left:10px;",
			"}"
		],

		"js" : [
			"function callMe(){",
			"",
			"	var nodeList = document.getElementsByClassName(\"segment\");",
			"",
			"	for(var i=0;i<nodeList.length;i++){",
			"		nodeList[i].innerHTML += \" <br\/> Selected by class\";",
			"	}",
			"",
			"	document.getElementById(\"seg3\").innerHTML +=  \" <br\/> Selected by id\";",
			"",
			"	nodeList = document.querySelectorAll(\"p.segment\");",
			"",
			"	for(var i=0;i<nodeList.length;i++){",
			"		nodeList[i].innerHTML += \" <br\/> Selected by css query\";",
			"	}",
			"	",
			"	document.getElementById(\"imgId\").src =  \"images\/JSlogo.png\";",
			"	var para = document.createElement(\"p\");",
			"	var node = document.createTextNode(\"This is new.\");",
			"	para.appendChild(node);",
			"	var element = document.getElementById(\"divId\");",
			"	element.appendChild(para);",
			"",
			"}"
		]

	},
	"JQ-ready" : {

		"html" : [
			"<p class=\"segment\">",
			"	Click on me",
			"</p>",
			"<p id=\"seg\"></p>",
			"<p id=\"seg\"></p>",
			"<p id=\"seg1\"></p>",
			"<input id=\"seg2\" type=\"text\"></input >"
		],

		"css" : [
			".segment{",
			"	background-color:green;",
			"	padding:5px;",
			"	width:150px;",
			"	height:75px;",
			"	font-weight:bold;",
			"	margin:10px;",
			"}"
		],

		"js" : [
			"$(document).ready(function(){",
			"    $(\"p\").click(function(){",
			"        $(this).hide();",
			"		 $(\"#seg\").html(\"Hidden !!\");",
			"		 $(\"#seg1\").text(\"Text \");",
			"		 $(\"#seg2\").val(\"Input value\");",
			"    });",
			"});"
		]

	},
	"JQ-DOMSelection" : {

		"html" : [
			"<br/>",
			"<button onclick=\"callMe()\">Process</button>",
			"",
			"<div class=\"segment\"> Segment 1</div>",
			"",
			"<p class=\"segment\"> Segment 2</p>",
			"",
			"<div class=\"segment1\" id=\"seg3\"> Segment 3</div>",
			"",
			"<img id=\"imgId\" src=\"images/download.png\" width=\"150\" height=\"132\"></img>",
			"",
			"<div id=\"divId\"></div>"
		],

		"css" : [
			".segment{",
			"	background-color:green;" ,
			"	padding:5px;" ,
			"	width:250px;" ,
			"	height:75px;" ,
			"	font-weight:bold;" ,
			"	margin:10px;" ,
			"}",
			"",
			"td{",
			"	padding:3px;",
			"}",
			"",
			".segment1{",
			"	background-color:gold;",
			"	padding:5px;",
			"	width:250px;",
			"	height:75px;",
			"	font-weight:bold;",
			"	margin:10px;",
			"}",
			"img{",
			"	margin:10px;",
			"}",
			"",
			"button{",
			"	margin:10px;",
			"}",
			""
		],

		"js" : [
			"function callMe(){",
			"	$(\".segment\").html($(\".segment\").html() + \"<br/> Selected by class\");",
			"	$(\"#seg3\").html($(\"#seg3\").html() + \"<br/> Selected by id\" );",
			"	$(\"#imgId\").attr('src','images/JSlogo.png');",
			"	$(\"p.segment\").html($(\"p.segment\").html() + \"<br/> Selected by tag name and class\");",
			"}"

		]

	},
	"JQ-events" : {

		"html" : [
			"<table>",
			"	<tr>",
			"		<td>",
			"			<div id=\"click\" class=\"segment\">",
			"				click",
			"			<\/div>",
			"		<\/td>",
			"		<td>",
			"			<span id=\"clickDisp\"><\/span>",
			"		<\/td>",
			"	<\/tr>",
			"	<tr>",
			"		<td>",
			"			<div id=\"mouseover\" class=\"segment\">",
			"				mouse over ",
			"			<\/div>",
			"		<\/td>",
			"		<td>",
			"			<span id=\"moverDisp\"><\/span>",
			"		<\/td>",
			"	<\/tr>",
			"	<tr>",
			"		<td>",
			"			<div id=\"mouseout\" class=\"segment\">",
			"				mouse out",
			"			<\/div>",
			"		<\/td>",
			"		<td>",
			"			<span id=\"moutDisp\"><\/span>",
			"		<td\/>",
			"	<\/tr>",
			"	<tr>",
			"		<td>",
			"			<input id=\"keydown\" type=\"text\"<\/input>",
			"		<\/td>",
			"		<td>",
			"			<span id=\"keydownDisp\"><\/span>",
			"		<\/td>",
			"	<\/tr>",
			"<!-- Once the value is changed , click outside -->",
			"	<tr>",
			"		<td>",
			"			<input id=\"change\" type=\"text\">",
			"<\/input>",
			"		<\/td>",
			"		<td>",
			"			<span id=\"onChangeDisp\"><\/span>",
			"		<\/td>",
			"	<\/tr>",
			"	<tr>",
			"		<td>",
			"			<div id=\"dblclick\" class=\"segment\">",
			"				double click",
			"			<\/div>",
			"		<\/td>",
			"		<td>",
			"			<span id=\"dblclickDisp\"><\/span>",
			"		<\/td>",
			"	<\/tr>",
			"	<tr>",
			"		<td>",
			"			<div id=\"mousedown\" class=\"segment\">",
			"				mouse down",
			"			<\/div>",
			"		<\/td>",
			"		<td>",
			"			<span id=\"mousedownDisp\"><\/span>",
			"		<\/td>",
			"	<\/tr>",
			"	<tr>",
			"		<td>",
			"			<div id=\"mouseup\" class=\"segment\">",
			"				mouse up",
			"			<\/div>",
			"		<\/td>",
			"		<td>",
			"			<span id=\"mouseupDisp\"><\/span>",
			"		<\/td>",
			"	<\/tr>",
			"	<tr>",
			"		<td>",
			"			<div id=\"hover\" class=\"segment\">",
			"				hover",
			"			<\/div>",
			"		<\/td>",
			"		<td>",
			"			<span id=\"hoverDisp\"><\/span>",
			"		<\/td>",
			"	<\/tr>",
			"	<tr>",
			"		<td>",
			"			<input id=\"hoverAndBlur\" type=\"text\">",
			"<\/input>",
			"		<\/td>",
			"		<td>",
			"			<span id=\"hoverDisp\"><\/span>",
			"		<\/td>",
			"	<\/tr>",
			"<\/table>"
		],

		"css" : [
			".segment{",
			"	background-color:green;",
			"	padding:1px;",
			"	width:150px;",
			"	height:20px;",
			"	font-weight:bold;",
			"	margin:2px;",
			"}",
			"",
			"td{",
			"	padding:3px;",
			"}"
		],

		"js" : [
			"$(document).ready(function(){",
			"	$(\"#click\").on(\"click\",function(){",
			"		callMe('click!!','clickDisp')",
			"	});",
			"	$(\"#mouseover\").on(\"mouseover\",function(){",
			"		callMe('mouse over!!','moverDisp')",
			"	});",
			"	$(\"#mouseout\").on(\"mouseout\",function(){",
			"		callMe('mouse out!!','moutDisp')",
			"	});",
			"	$(\"#keydown\").on(\"keydown\",function(){",
			"		callMe('keydown!!','keydownDisp')",
			"	});",
			"	$(\"#change\").on(\"change\",function(){",
			"		callMe('change!!','onChangeDisp')",
			"	});",
			"	$(\"#dblclick\").on(\"dblclick\",function(){",
			"		callMe('dblClick!!','dblclickDisp')",
			"	});",
			"	$(\"#mousedown\").on(\"mousedown\",function(){",
			"		callMe('mousedown!!','mousedownDisp')",
			"	});",
			"	$(\"#mouseup\").on(\"mouseup\",function(){",
			"		callMe('mouseup!!','mouseupDisp')",
			"	});",
			"	$(\"#hover\").hover(function(){",
			"		$(this).css(\"background-color\",\"gold\");",
			"	});",
			"	$(\"#hoverAndBlur\").focus(function(){",
			"		$(this).css(\"background-color\",\"grey\");",
			"	});",
			"	$(\"#hoverAndBlur\").blur(function(){",
			"		$(this).css(\"background-color\",\"white\");",
			"	});",
			"});",
			"	",
			"function callMe(str,id){",
			"	$(\"#\"+id).html(str);",
			"}"
		]

	},
	"JQ-effects" : {

		"html" : [
			"<br/>",
			"<p class=\"segment\"></p>",
			"<br/>",
			"<div id=\"buttonsDiv\">",
			"<button id=\"hide\">Hide</button>",
			"<button id=\"show\">Show</button>",
			"<button id=\"toggle\">Toggle</button>",
			"<button id=\"fadeTo\">Fade to</button>",
			"<button id=\"fadeToFull\">Fade In full</button>",
			"<button id=\"fade\">Fade in</button>",
			"<button id=\"fadeSlow\">Fade in Slowly</button>",
			"<br/>",
			"<button id=\"fadeTime\">Fade in 3000 ms</button>",
			"<button id=\"fadeOut\">Fade out</button>",
			"<button id=\"fadeOutSlow\">Fade out Slowly</button>",
			"<button id=\"fadeOutTime\">Fade out 3000 ms</button>",
			"<br/>",
			"<button id=\"fadeToggle\">Fade toggle</button>",
			"<button id=\"fadeToggleSlow\">Fade toggle Slowly</button>",
			"<button id=\"fadeToggleTime\">Fade toggle 3000 ms</button>",
			"<button id=\"chainingSliding\">Chaining Sliding</button>",
			"<br/>",
			"<button id=\"addClass\">Add border class</button>",
			"<button id=\"removeClass\">Remove border class</button>",
			"<button id=\"toggleClass\">Toggle border class</button>",
			"<br/>",
			"<button id=\"slideDown\">Slide down</button>",
			"<button id=\"slideUp\">Slide up</button>",
			"<button id=\"stop\">Stop sliding</button>",
			"<button id=\"slideToggle\">Toggle sliding</button>",
			"<button id=\"animate\">Animate</button>",
			"</div>"
		],

		"css" : [
			".segment{",
			"	background-color:green;",
			"	padding:1px;",
			"	width:100px;",
			"	height:100px;",
			"	font-weight:bold;",
			"	margin:2px;",
			"	position:absolute;",
			"}",
			"",
			"#buttonsDiv{",
			"	position:absolute;",
			"	top:130px;",
			"}",
			".addBorder{",
			"	border:5px solid black;",
			"}",
			"button{",
			"	margin:5px;",
			"}	"
		],

		"js" : [
			"$(document).ready(function(){",
			"    $(\"#hide\").click(function(){",
			"        $(\"p\").hide();",
			"    });",
			"    $(\"#show\").click(function(){",
			"        $(\"p\").show();",
			"    });",
			"    $(\"#toggle\").click(function(){",
			"        $(\"p\").toggle();",
			"    });",
			"    $(\"#fade\").click(function(){",
			"        $(\"p\").fadeIn();",
			"    });",
			"    $(\"#fadeSlow\").click(function(){",
			"        $(\"p\").fadeIn(\"slow\");",
			"    });",
			"    $(\"#fadeTime\").click(function(){",
			"        $(\"p\").fadeIn(3000);",
			"    });",
			"    $(\"#fadeOut\").click(function(){",
			"        $(\"p\").fadeOut();",
			"    });",
			"    $(\"#fadeOutSlow\").click(function(){",
			"        $(\"p\").fadeOut(\"slow\");",
			"    });",
			"    $(\"#fadeOutTime\").click(function(){",
			"        $(\"p\").fadeOut(3000);",
			"    });",
			"    $(\"#fadeToggle\").click(function(){",
			"        $(\"p\").fadeToggle();",
			"    });",
			"    $(\"#fadeToggleSlow\").click(function(){",
			"        $(\"p\").fadeToggle(\"slow\");",
			"    });",
			"    $(\"#fadeToggleTime\").click(function(){",
			"        $(\"p\").fadeToggle(3000);",
			"    });",
			"    $(\"#fadeTo\").click(function(){",
			"        $(\"p\").fadeTo(\"slow\",\"0.5\");",
			"    });	",
			"    $(\"#fadeToFull\").click(function(){",
			"        $(\"p\").fadeTo(\"slow\",\"1.0\");",
			"    });	",
			"    $(\"#addClass\").click(function(){",
			"        $(\"p\").addClass(\"addBorder\");",
			"    });",
			"    $(\"#removeClass\").click(function(){",
			"        $(\"p\").removeClass(\"addBorder\");",
			"    });	",
			"    $(\"#toggleClass\").click(function(){",
			"        $(\"p\").toggleClass(\"addBorder\");",
			"    });	",
			"    $(\"#slideUp\").click(function(){",
			"        $(\"p\").slideUp(\"slow\");",
			"    });",
			"    $(\"#slideDown\").click(function(){",
			"        $(\"p\").slideDown(5000);",
			"    });	",
			"    $(\"#slideToggle\").click(function(){",
			"        $(\"p\").slideToggle();",
			"    });	",
			"    $(\"#animate\").click(function(){",
			"        $(\"p\").animate({left: '250px'});",
			"    });	",
			"   $(\"#chainingSliding\").click(function(){",
			"        $(\"p\").slideUp(\"slow\").slideDown(\"slow\");",
			"    });	",
			"	$(\"#stop\").click(function(){",
       		"	$(\"p\").stop();",
    		"	});	",
			"});"
		]

	},
	"JQ-traversing" : {

		"html" : [
			"<div class=\"segment\" >",
			"	Layer 1",
			"	<div class=\"segment\" id=\"layer2source1\">",
			"		Layer 2",
			"		<p class=\"segment\">A Sibling</p>",
			"		<p class=\"segment\" id=\"layer3source2\">",
			"			<span class=\"segment\">Layer 3</span><span class=\"segment\">Layer 3</span>",
			"		</p>",
			"		<p class=\"segment\">A Sibling</p>",
			"		<br/>",
			"		<div class=\"segment\">Layer 3</div>",
			"	</div>",
			"</div>"
		],

		"css" : [
			".segment{",
			"	border:1px solid black;",
			"	padding:5px;",
			"	margin:5px;",
			"	cursor:pointer;",
			"}"
		],

		"js" : [
			"$(document).ready(function(){",
			"    $(\"#layer3source2\").append(\"Appended\");",
			"    $(\"#layer3source2\").prepend(\"Prepended\");",
			"    $(\"#layer3source2\").parents(\"div\").css({\"background-color\": \"royalBlue\"});",
			"    $(\"#layer3source2\").css({\"background-color\": \"gold\"});",
			"    $(\"#layer3source2\").parent().css({\"background-color\": \"powderBlue\"});",
			"    $(\"#layer3source2\").before(\"Before\");",
			"    $(\"#layer3source2\").after(\"After\");",
			"    $(\"#layer2source1\").children().css({\"border\": \"3px solid black\"});	",
			"    $(\"#layer3source2\").siblings().css({\"border\": \"3px solid blue\"});	",
			"    $(\"#layer3source2\").next().css({\"border\": \"3px solid yellow\"});	",
			"    $(\"#layer3source2\").prev().css({\"border\": \"3px solid orange\"});	",
			"    $(\"#layer3source2\").find(\"span\").css({\"background-color\": \"green\"});",
			"    $(\"#layer2source1\").children().filter(\"div\").css({\"background-color\": \"red\"});",
			"});"

		]

	}

};